package cn.xianbin.queryengine.error.parameter;

public enum QueryParameterErrorType {

    PROJECT_NOT_EXISTS,
    EVENT_NOT_EXISTS,
    EVENT_INVISIBLE,
    EVENT_UNAUTHORIZED,
    PROPERTY_NOT_EXISTS,
    PROPERTY_INVALID,
    FILTER_PARAMETER_NUM_INVALID,
    FILTER_PARAMETER_DATA_TYPE_INVALID,
    FILTER_FUNCTION_INVALID,
    CUSTOM_INDICATOR_INVALID,
    PROJECT_NOT_READY,
    SESSION_NOT_EXISTS,
    UNSUPPORTED_MEASURE_TYPE,
    UNSUPPORTED_BY_FIELD,
    USER_TAG_NOT_READY,
    PARAMETER_FORMAT_ERROR,
    PATH_ANALYSIS_PARAMETER_INVALID,
    FUNNEL_NOT_EXISTS;
}
